### ISSUE TITLE
The json feed is not generated correctly

### ISSUE THREAD

**Issue by Lazzu** [cobalt-org/cobalt.rs#1137]
I'm moving to Cobalt from Zola as I'm interested in all things Rust now.

I have my posts sorted in folders for each year they were written in. When generating the json feed the URL points to `/posts/post.html` instead of `/posts/year/post.html`.

Also the tags are not populated in the json feed.

`/posts/2021/hello-world.md`
```yaml
layout: default.liquid
title: "Hello, World!"
description: "<snip-snap-lengthy-text>"
published_date: "2021-06-26 00:00:00 +0300"
tags: 
    - "blog-meta"
is_draft: false
data: 
    author: "Lasse Numminen"
```

This produces following json:
```json
{
  "items": [
    {
      "id": "https://<website>/posts/hello-world.html",
      "url": "https://<website>/posts/hello-world.html",
      "title": "Hello, World!",
      "content_html": "<snip-snap-lengthy-text>",
      "content_text": null,
      "date_published": "Sat, 26 Jun 2021 00:00:00 +0300",
      "tags": []
    }]
}
```
