### ISSUE TITLE
Multiblog

### ISSUE THREAD

**Issue by harrymkt** [cobalt-org/cobalt.rs#1208]
Hello.

Can I have multiple blogs in a single Cobalt site?
For example, in config like this.

```YAML
posts:
  title: Blog
dir: blog
posts2:
  title: Useful articles
  dir: articles
```

And access with `paginator`, `paginator2`, etc.

Thanks!

**Comment by matbrgz** [comment]
Hi @harrymkt and team,

This is a great request—supporting **multiple blogs** alongside **theming** would make Cobalt even more flexible. A few thoughts on how it could work:

1. **Multi-blog support via named collections**

   ```yaml
   posts:
     title: "Main Blog"
     dir: "blog"
   posts2:
     title: "Useful Articles"
     dir: "articles"
   ```

   * Each collection gets its own paginator (e.g. `paginator`, `paginator2`).
   * Permalinks, tags, and layouts can be scoped per collection.

2. **Per-collection theming**

   * Extend `_cobalt.yml` to allow a `theme` field on each collection:

     ```yaml
     posts:
       title: "Main Blog"
       dir: "blog"
       theme: "modern"
     posts2:
       title: "Useful Articles"
       dir: "articles"
       theme: "classic"
     ```
   * This would load layouts, includes, and assets from `_theme/modern/…` or `_theme/classic/…` depending on the collection.

3. **Shared vs. collection-specific assets**

   * A global theme (e.g. in `_theme/default/`) applies to pages without an explicit `theme`.
   * Collection themes could override only layouts or styles, falling back to the global theme where not defined.

4. **Implementation sketch**

   * During the build, read each collection’s `theme` and merge its `_theme/<slug>` folder into the Liquid include and layout search path.
   * Generate separate paginators and feed files per collection, honoring the selected theme.

By combining named collections with scoped theming, you get **multiple, independently styled blogs** in one site. Happy to help prototype or iterate on this design—let me know what you think!
