### ISSUE TITLE
RSS should support either summaries or full articles

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#309]
Inspired from https://blog.flameeyes.eu/2017/07/why-i-do-not-like-hugo/

**Comment by epage** [comment]
Concern about breaking change is what will the config format look like?

**Comment by epage** [comment]
The nesting becomes even worse when we add collections

```yml
assets:
  sass:
    style: Nested
posts:
  order: Desc
  feed:
    rss_path: ~
    jsonfeed_path: ~
    content: description
    limit: 200
collections:
  talks:
    order: Desc
    feed:
      rss_path: ~
      jsonfeed_path: ~
      content: description
      limit: 200
```

**Comment by mnivoliez** [comment]
Why not use something like
```yaml
assets: 
  sass: 
    style: Nested 
posts: 
  order: Desc 
collections: 
  talks: 
  order: Desc
feeds:
  from:
    - posts
    - collections:talks
  content: description 
  limit: 200
  rss_path: ~
  jsonfeed_path: ~
```

**Comment by Geobert** [comment]
Nesting is bug prone for cobalt's developers, and bug prone for the user as well. 
I prefer flat :)

**Comment by epage** [comment]
@Geobert 
> Nesting is bug prone for cobalt's developers,

I'm not aware of it being error prone for development.  Is there something in particular you are thinking of?

**Comment by Geobert** [comment]
More parameters to manage (level on indentation, error detection, recovery on parsing error…)

**Comment by epage** [comment]
@mnivoliez 
> Why not use something like

Intriguing take.   A benefit to this is it makes it possible to support RSS feeds that cross collections.

Some modifications we'd need to make:
- Support more than one feed, like allowing a feed per collection
- Sort order needs to be consolidated cross-collection.  We still need it per-collection for `collection.pages` (see #323) but if two different collections have different sort orders, we'd need a way to know how to merge them

```yml
assets: 
  sass: 
    style: Nested 
posts: 
  order: Desc 
collections: 
  talks: 
    order: Asc
feeds:
  - from:
      - posts
    content: description 
    limit: 200
    rss_path: posts.xml
    jsonfeed_path: posts.json
    order: Desc 
  - from:
      - talks
    content: description 
    limit: 200
    rss_path: talks.yml
    jsonfeed_path: talks.json
    order: Desc 
  - from:
      - posts
      - talks
    content: description 
    limit: 200
    rss_path: all.yml
    jsonfeed_path: all.json
    order: Desc 
```

**Comment by epage** [comment]
Another important consideration I've been taking in Cobalt's design is to keep the configuration minimal for people who don't need advanced features.

So if you are just maintaining a blog and want to add an RSS feed, today that looks like 
```yml
rss: posts.xml
```
with this proposal it'd look like
```yml
feeds:
  - from:
      - posts
    rss_path: posts.xml
```

We can simplify this further by allowing `from` to either be a collection name or a list of collection names.  I think this makes sense because the 90% case will probably be a feed per collection.
```yml
feeds:
  - from: posts
    rss_path: posts.xml
```

We could also default `from` to be `posts`, making it
```yml
feeds:
  - rss_path: posts.xml
```

We could go even further and allow `feeds` to be either one item or a list, so it could be
```yml
feeds:
  rss_path: posts.xml
```
My concerns
- This is going too far into "magic"
- `feeds` being plural will throw this off

A counter to that last one
```yml
feeds:
  rss_path: posts.xml
  json_path: posts.json
```
Technically, that is more than one feed.

Thoughts?

**Comment by epage** [comment]
Another consideration is I've been moving Cobalt to be consistent in naming.

Examples:
- Instead of a frontmatter having an `extends` field that contains a layout, I just called it `layout`.
- Calling the relative path to a file `permalink` when customizing it in the frontmatter and for the variable (`{{ page.permalink }}`)
- etc

So `from` would be better called `collections`.

```yml
assets: 
  sass: 
    style: Nested 
posts: 
  order: Desc 
collections: 
  talks: 
    order: Asc
feeds:
  - collections: posts
    rss_path: posts.xml
    jsonfeed_path: posts.json
  - collections:
      - posts
      - talks
    rss_path: all.yml
    jsonfeed_path: all.json
```

This runs into the pluralization problem of `feeds` when used with the idea that `collections` can be a string or a list of strings.

**Comment by epage** [comment]
@Geobert 
> > > Nesting is bug prone for cobalt's developers,

@epage
> > I'm not aware of it being error prone for development. Is there something in particular you are thinking of?

@Geobert 
> More parameters to manage (level on indentation, error detection, recovery on parsing error…)

Half of that is covered by the yaml parser.  The other half is covered by serde.

To add a level of indentation to this
```rust
struct PostBuilder {
    ...
    rss: Option<String>,
    ...
}
```
just means changing it to
```rust
struct FeedBuilder {
    rss: Option<String>,
}

struct PostBuilder {
    ...
    rss: FeedBuilder,
    ...
}
```
and the code gets verified by the compiler that its correct.

**Comment by Geobert** [comment]
Ok for the dev side, nice :) What about the user side?

**Comment by epage** [comment]
> Ok for the dev side, nice :) What about the user side?

That is why I didn't just go forward with nesting but decided to ask :)

**Comment by epage** [comment]
Given the current format
```yml
assets:
  sass:
    style: Nested
posts:
  order: Desc
  rss: ~
  jsonfeed: ~
```
I was planning on exposing the feed permalinks as 
- `{{ collection.rss_permalink }}`
- `{{ collection.jsonfeed_permalink }}`

This would make it easy for themes to expose the feeds without worrying about what the user configured them to.

But with
```yml
assets: 
  sass: 
    style: Nested 
posts: 
  order: Desc 
collections: 
  talks: 
    order: Asc
feeds:
  - collections: posts
    rss_path: posts.xml
    jsonfeed_path: posts.json
  - collections:
      - posts
      - talks
    rss_path: all.yml
    jsonfeed_path: all.json
```
How would we expose the permalinks?

It could look something like:
```
{% for feed in feeds %}
  {% for feed_collection in feed.collections %}
    {% if collection.slug == feed_collection %}
{{ feed.rss_permalink }}
    {% endif %}
  {% endfor %}
{% endfor %}
```
(be real helpful to have https://github.com/cobalt-org/liquid-rust/issues/155)

**Comment by epage** [comment]
In refining this idea more, what if we changed:
```yml
feeds:
  - collections: posts
    rss_path: posts.xml
    jsonfeed_path: posts.json
```
to (without defaults)
```yml
  - collections:
      - posts
    content: description
    limit: 20
    permalink: posts.xml
    format: rss
  - collections:
      - posts
    content: description
    limit: 20
    permalink: posts.json
    format: jsonfeed
```
We could default `format` based on `permalink`'s extension, like we do with frontmatter's `format`.

Pros
- Better scalability

Cons
- Requires duplication for re-skinning the same content in a different format
- User needs to filter their `{% for feed in feeds %}` with a check for `feed.format`.
- (Implementation) if user wants both jsonfeed / rss, requires re-generating list of pages for each
