### ISSUE TITLE
Support generating thumbnails

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#318]
Some collections will need smaller sizes of images for faster loading (think image gallery).

Config
```yaml
assets:
  - thumbnails:
    - permalink: /:path/:filename.:output_ext
      exclude:
      size:
```
