### ISSUE TITLE
Add default permlink format

### ISSUE THREAD

**Issue by berkus** [cobalt-org/cobalt.rs#441]
Currently only available permlink default is for posts, as `posts.default.permlink` in _cobalt.yml, I propose to add a site-wide default permlink format as `site.default.permlink`.

Setting Inheritance would look like
`site.default.permlink`
+-may be overridden by `posts.default.permlink` in posts
   +-overridden by `permlink` in frontmatter

**Comment by epage** [comment]
This already exists today as `default`.

See https://cobalt-org.github.io/docs/config.html

**Comment by berkus** [comment]
Are these `pages.default`? I didn't find it in the docs for some reason, that's why i created this.

**Comment by epage** [comment]
From the example in the documentation
```yml
# Page/Post options
default:
  excerpt_separator: "\n\n"
  is_draft: false
syntax_highlight:
  theme: "base16-ocean.dark"
assets:
  sass:
    style: Nested
pages:
  default: {}
posts:
  title: ~
  description: ~
  dir: posts
  drafts_dir: _drafts
  order: Desc
  rss: ~
  jsonfeed: ~
  default: {}
```

There are three different `default`
- `default`
- `pages.default`
- `posts.default`

This is further explained in the `Pages and Posts` section of that page.
