### ISSUE TITLE
Add path as a document attribute

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#47]
It would be useful to have the output path (relative to the final destination) of a certain file for usage when rendering that file or when listing e.g. blog posts. In my own blog I currently have to do this:
```yaml
title:   Using rustfmt in Vim
date:    03 Nov 2015 23:00:00 +0100
path:    rustfmt-vim.html
```
Not very nice.
