### ISSUE TITLE
[Bug] Pagination's permalink index are embedded into {{include}}

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#622]
Continuation of https://github.com/cobalt-org/cobalt.rs/issues/618#issuecomment-478261676

Ok, after reviewing my code, something is wrong with how I treat the pagination's
permalink (vs front's permalink, as atm, both have the same same).

I have different "1st": 
* the first paginator, which uses fron't permalink
* the page 1 of an index.

In the case of `All` they are the same.

In the case of `Tags`, we have the 1st paginator using front's permalink which has
`indexes` field. Then we have a paginated index per tag, page 1 being forced to
`tags/my_tag`, other pages being interpreted with the following caveat: `{{include}}` is
forced to `tags/my_tag`. 

In the case of `Categories`, it's the same, I embed the needed categories into
`{{include}}` which contains, for exemple, `categories/category1/subcategoryA`.

So I didn't interpret how we treat `<index>` in the permalink, I embedded it into
`include`, which is wrong.

So, let's specify it properly now that I have more knowledge on the subject ^^' and I
think I'll take @epage proposal.
# Current Proposal
## All
```
permalink: /
pagination:
  include: All
  permalink_suffix: ./{{num}}/
```

* `/index.html`
* `/all/2/index.html`

### Example 1
```
permalink: /tags_page.html
pagination:
  include: Tags
  permalink_suffix: ./{{num}}/
```

* `/tags_page.html`
* `/tags_page/my_tag/index.html`
* `/tags_page/my_tag/2/index.html`

### Example 2
```
permalink: /tags
pagination:
  include: Tags
  permalink_suffix: ./{{num}}/
```

* `/tags/index.html`
* `/tags/my_tag/index.html`
* `/tags/my_tag/2/index.html`

## Spec

* calculate `pagination_root` using `permalink`: if directory nothing to do, if file,
  remove extension
* All: 1st paginator uses `permalink`, the rest uses
  `pagination_root + index + permalink_suffix` (`index` = "all")
* Tags/Categories: meta paginator uses `permalink`, 1st paginator for one `index` uses
  `paginator_root + index`, the rest uses `paginator_root + index + permalink_suffix`
* Dates: same, meta paginator lists the biggest time unit, `index` span defined by
  `date_index`
---
# Former proposal below
## Proposal 1
If frontmatter's `permalink` is a folder, we use it as index "root". If frontmatter's
`permalink` is a file, we remove the extension, and use the value as index "root". Under
`pagination`, we have `permalink_suffix` which defines what we add to "root" to construct
the indexes' path.

Values that can be used:
* all the normal values in a permalink
* `{{include}}`: interpreted as `all`, `tags`, `categories`, `dates` according to the
  current include
* `{{index}}`: interpreted as current index value

## Proposal 2
Do not use frontmatter's `permalink`.

```yml
pagination:
  root_permalink: /{{include}} //default value
  sub_pages_suffix: ./{{index}}/_p/{{num}} //default value
```

With both fields using the same values as defined in proposal 1.

## Proposal 3

Same as proposal 1, adding support for `{{include}}` to frontmatter's permalink.

**Comment by epage** [comment]
RE Proposal 1

So there are
- `permalink` (in frontmatter) defines the root page
- root path: the parent directory for all 1st pages and 2nd+ pages
- `permalink_suffix` (in pagination) used for 2nd+ pages, appended to root path

Personally, I would expect the suffix to be a suffix to the current 1st page rather than only the root page.  This means a user does not include `{{index}}` in their `permalink_suffix`.

Alternatively, we could make `{{index}}` available for `permalink`, with it evaluating to a blank string for the root page.  I can't see a reason why someone would do anything besides having `{{index}}` at the end but this would at least make things explicit which might help people understand whats going on.

**Comment by Geobert** [comment]
Not sure to understand you, here is an example:
```
permalink: /tags.html
pagination:
  include: Tags
  permalink_suffix: ./{{index}}/_p/{{num}}/
```

giving us:
* `/tags.html`
* `/tags/my_tag/index.html`
* `/tags/my_tag/_p2/index.html`

Another example:
```
permalink: /tags/
pagination:
  include: Tags
  permalink_suffix: ./{{index}}/_p{{num}}/
```

* `/tags/index.html`
* `/tags/my_tag/index.html`
* `/tags/my_tag/_p2/index.html`

And I realize that `{{include}}` is useless in Proposal 1

**Comment by epage** [comment]
So getting back to my question in the other thread, describe to me what user input and machine input is being used to create `/tags/my_tag/index.html` under Proposal 1.

**Comment by Geobert** [comment]
Ok, writing it showed me the issue: we can't have `/tags/my_tag/index.html`.

But I was like how to make `All` work then and I write this:

```
permalink: /
pagination:
  include: All
  permalink_suffix: ./{{include}}/_p/{{num}}/
```

Read all posts, take `per_page` and create a paginator with permalink set to `/index.html`
then, for each `per_page` posts, create a paginator with permalink set to `permalink` +
`permalink_suffix`: `/all/_p/2/index.html`.

```
permalink: /tags.html
pagination:
  include: Tags
  permalink_suffix: ./{{index}}/_p/{{num}}/
```

Distribute all posts per tags. 

Take permalink and transforms to `root` (remove extension if needed): `/tags`. 

For each tag, take the first `per_page` posts and create a paginator
with permalink set to `root` + `permalink_suffix`: `/tags/current_tag/_p/1/index.html`

Keep reference of the 1st paginator of each tag.

Insert at 1st position of all the paginators, a paginator with field `indexes` filled with
all the 1st paginator of each tag.
