### ISSUE TITLE
Support all fields from the RSS spec

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#63]
The RSS spec defines a lot of optional fields that we do not support right now. We should accept more arguments through both the config file (for page-wide fields) and in the article front-matter (for article fields).

See http://cyber.law.harvard.edu/rss/rss.html

**Comment by LucioFranco** [comment]
@johannhof I did some looking into this. I believe that we should restructure the config file to support most of the optional fields but have them be all under an `rss` attribute. Example:

```
rss:
  path: rss.xml
  name: My blog!
  description: Blog description
  link: http://example.com
  language: en-US
  generator: cobalt
```

Then allow them to define other optional ones. This would allow users to add other items in the config and not have it clutter. So I think we should move this issue to the next release and decide on a better config format. What do you think?
