### ISSUE TITLE
publish_date_in_filename does not work in pages config context

### ISSUE THREAD

**Issue by koitsu** [cobalt-org/cobalt.rs#778]
# Version

0.15.11

# Details

The Cobalt documentation says that `publish_date_in_filename` is supported both `posts` and `pages` config contexts: https://cobalt-org.github.io/docs/config/

However, the config parser disagrees -- it works in `posts` but not `pages`:

```
Error: serve command failed
Info: caused by Error reading config file "/home/jdc/cobalt/blog/_cobalt.yml"
Info: caused by pages: unknown field `publish_date_in_filename`, expected `default` at line 34 column 3
```

Lines 25 through 37 of `_cobalt.yml`:

```yaml
posts:
  dir: "blog"
  drafts_dir: "_drafts"
  publish_date_in_filename: true
  default: {
    layout: "default.liquid"
  }

pages:
  publish_date_in_filename: false
  default: {
    layout: "default.liquid"
  }
```

Not sure if this is a documentation issue or an issue with https://github.com/cobalt-org/cobalt.rs/issues/562.
