### ISSUE TITLE
support menues

### ISSUE THREAD

**Issue by flosse** [cobalt-org/cobalt.rs#89]
It would be great to be able to define a menu within the configuration file.

**Comment by LucioFranco** [comment]
What type of menu are you talking about? You can create your own menu with css. Are you talking about adding our own menus that you can just enable?

**Comment by flosse** [comment]
I'd like to define a menu structure like this

```yaml
menu:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
```
to use it within a navigation template.
